package com.example.Estore.Estore.Shared.dto.Product;

import java.io.Serializable;

public class CategoryDto implements Serializable {

    private Long categoryId;
    private String CategoryName;

    /**
     * Method is used to get category id
     * @return long
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * Method is used to set  category id
     * @param categoryId autogenerated category id
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Method is used to get category name
     * @return string
     */
    public String getCategoryName() {
        return CategoryName;
    }

    /**
     * Method is used to set category name
     * @param categoryName, entered by admin
     */
    public void setCategoryName(String categoryName) {
        CategoryName = categoryName;
    }
}
