package com.example.Estore.Estore.Shared.dto.Product;

import javax.persistence.Column;
import java.io.Serializable;

public class ProductDto implements Serializable {

    private Long productId ;
    private String productName;
    private String description;
    private int price;
    private int quantity;
    private String categoryName;

    /**
     * Method is used to get categoryname.
     * @return string
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Method is used to set category name
     * @param categoryName category name entered by seller
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * Method is used to get productId
     * @return Long
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * Method is used to set productId
     * @param productId autogenerated unique product id
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Method is used to get product name
     * @return string
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Method is used to set product name
     * @param productName product name entered by seller
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Method is used to get product description
     * @return string
     */
    public String getDescription() {
        return description;
    }

    /**
     * Method is used to set product description
     * @param description product description entered by seller
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Method is used to get product price
     * @return int
     */
    public int getPrice() {
        return price;
    }

    /**
     * Method is used to set product price
     * @param price price entered by seller
     */
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * Method is used to get product quantity
     * @return int
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Method is used to set product description
     * @param quantity, entered by seller
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
